export const REQUEST_ACTION = "REQUEST_ACTION";
export const REQUEST_FAILED_ACTION = "REQUEST_FAILED_ACTION";
export const LOGIN_ACTION = "LOGIN_ACTION";
export const REGISTER_ACTION = "REGISTER_ACTION";
export const LOGOUT_ACTION = "LOGOUT_ACTION";