export const REQUEST_ACTION_AUTH = "REQUEST_ACTION_AUTH";
export const REQUEST_SUCCESS_ACTION_AUTH = "REQUEST_SUCCESS_ACTION_AUTH";
export const REQUEST_FAILED_ACTION_AUTH = "REQUEST_FAILED_ACTION_AUTH";
export const LOGIN_COMPANY_ACTION = "LOGIN_COMPANY_ACTION";
export const LOGIN_ACTION = "LOGIN_ACTION";
export const REGISTER_ACTION = "REGISTER_ACTION";
export const LOGOUT_ACTION = "LOGOUT_ACTION";
