export const REQUEST_ACTION_COMPANIES = "REQUEST_ACTION_COMPANIES";
export const REQUEST_SUCCESS_ACTION_COMPANIES = "REQUEST_SUCCESS_ACTION_COMPANIES";
export const REQUEST_FAILED_ACTION_COMPANIES = "REQUEST_FAILED_ACTION_COMPANIES";
export const GET_ALL_COMPANIES = "GET_ALL_COMPANIES";
export const GET_COMPANY = "GET_COMPANY";
export const CREATE_COMPANY = "CREATE_COMPANY";
export const UPDATE_COMPANY = "UPDATE_COMPANY";
export const DELETE_COMPANY = "DELETE_COMPANY";
