export const REQUEST_ACTION_JOBS = "REQUEST_ACTION_JOBS";
export const REQUEST_SUCCESS_ACTION_JOBS = "REQUEST_SUCCESS_ACTION_JOBS";
export const REQUEST_FAILED_ACTION_JOBS = "REQUEST_FAILED_ACTION_JOBS";
export const GET_ALL_JOBS = "GET_ALL_JOBS";
export const GET_JOB = "GET_JOB";
export const CREATE_JOB = "CREATE_JOB";
export const UPDATE_JOB = "UPDATE_JOB";
export const DELETE_JOB = "DELETE_JOB";
