export const REQUEST_ACTION_LECTURES = "REQUEST_ACTION_LECTURES";
export const REQUEST_SUCCESS_ACTION_LECTURES = "REQUEST_SUCCESS_ACTION_LECTURES";
export const REQUEST_FAILED_ACTION_LECTURES = "REQUEST_FAILED_ACTION_LECTURES";
export const GET_ALL_LECTURES = "GET_ALL_LECTURES";
export const GET_LECTURE_BY_ID = "GET_LECTURE_BY_ID";
export const CREATE_LECTURE = "CREATE_LECTURE";
export const UPDATE_LECTURE = "UPDATE_LECTURE";
export const DELETE_LECTURE = "DELETE_LECTURE";
