export const REQUEST_ACTION_MODULES = "REQUEST_ACTION_MODULES";
export const REQUEST_SUCCESS_ACTION_MODULES = "REQUEST_SUCCESS_ACTION_MODULES";
export const REQUEST_FAILED_ACTION_MODULES = "REQUEST_FAILED_ACTION_MODULES";
export const GET_ALL_MODULES = "GET_ALL_MODULES";
export const GET_MODULE_BY_ID = "GET_MODULE_BY_ID";
export const CREATE_MODULE = "CREATE_MODULE";
export const UPDATE_MODULE = "UPDATE_MODULE";
export const DELETE_MODULE = "DELETE_MODULE";
