export const REQUEST_ACTION_TALKS = "REQUEST_ACTION_TALKS";
export const REQUEST_SUCCESS_ACTION_TALKS = "REQUEST_SUCCESS_ACTION_TALKS";
export const REQUEST_FAILED_ACTION_TALKS = "REQUEST_FAILED_ACTION_TALKS";
export const GET_ALL_TALKS = "GET_ALL_TALKS";
export const GET_TALK = "GET_TALK";
export const CREATE_TALK = "CREATE_TALK";
export const UPDATE_TALK = "UPDATE_TALK";
export const DELETE_TALK = "DELETE_TALK";
