# Get all talks

GET http://localhost:5000/talk

###

# Get one talk

GET http://localhost:5000/talk/6019a0156011a30f70690e0e

###

# Create one talk

POST http://localhost:5000/talk
Content-Type: application/json

{
  "title": "Promesas",
  "imagen": ":)",
  "description": "Todo sobre promesas",
  "url": "www.url.com"
}

###

# Update one talk

PATCH http://localhost:5000/talk/6019a0156011a30f70690e0e
Content-Type: application/json

{
  "title": "Modulo 2",
  "imagen": "(L)",
  "description": "Javascript retrasado",
  "url": " "
}

###

# Delete one talk

DELETE  http://localhost:5000/talk/6019eaed0a1cc80cbc8fd49b

###
